[2025-01-12T19:02:50.248+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-12T19:02:50.423+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sber_autopodpiska.main_sessions manual__2025-01-12T18:43:11.976890+00:00 [queued]>
[2025-01-12T19:02:50.438+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sber_autopodpiska.main_sessions manual__2025-01-12T18:43:11.976890+00:00 [queued]>
[2025-01-12T19:02:50.457+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-12T19:02:50.563+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): main_sessions> on 2025-01-12 18:43:11.976890+00:00
[2025-01-12T19:02:50.574+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'sber_autopodpiska', 'main_sessions', 'manual__2025-01-12T18:43:11.976890+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/diploma_dag.py', '--cfg-path', '/tmp/tmpq1a5brpl']
[2025-01-12T19:02:50.577+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask main_sessions
[2025-01-12T19:02:50.633+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=306) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-12T19:02:50.634+0000] {standard_task_runner.py:72} INFO - Started process 308 to run task
[2025-01-12T19:02:50.778+0000] {task_command.py:467} INFO - Running <TaskInstance: sber_autopodpiska.main_sessions manual__2025-01-12T18:43:11.976890+00:00 [running]> on host 95f5aa5474ee
[2025-01-12T19:02:51.003+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='sber_autopodpiska' AIRFLOW_CTX_TASK_ID='main_sessions' AIRFLOW_CTX_EXECUTION_DATE='2025-01-12T18:43:11.976890+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-12T18:43:11.976890+00:00'
[2025-01-12T19:02:51.004+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-12T19:03:11.538+0000] {job.py:229} INFO - Heartbeat recovered after 15.84 seconds
[2025-01-12T19:03:16.800+0000] {job.py:229} INFO - Heartbeat recovered after 16.00 seconds
[2025-01-12T19:03:22.480+0000] {main_sessions.py:54} INFO - filename is /opt/***/data/diploma_main_dataset/ga_sessions.csv
[2025-01-12T19:03:34.722+0000] {logging_mixin.py:190} WARNING - --- Logging error ---
[2025-01-12T19:03:34.724+0000] {logging_mixin.py:190} WARNING - Traceback (most recent call last):
[2025-01-12T19:03:34.725+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1160, in emit
    msg = self.format(record)
          ^^^^^^^^^^^^^^^^^^^
[2025-01-12T19:03:34.725+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 999, in format
    return fmt.format(record)
           ^^^^^^^^^^^^^^^^^^
[2025-01-12T19:03:34.726+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 703, in format
    record.message = record.getMessage()
                     ^^^^^^^^^^^^^^^^^^^
[2025-01-12T19:03:34.727+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 392, in getMessage
    msg = msg % self.args
          ~~~~^~~~~~~~~~~
[2025-01-12T19:03:34.727+0000] {logging_mixin.py:190} WARNING - TypeError: not all arguments converted during string formatting
[2025-01-12T19:03:34.728+0000] {logging_mixin.py:190} WARNING - Call stack:
[2025-01-12T19:03:34.863+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/bin/***", line 8, in <module>
    sys.exit(main())
[2025-01-12T19:03:34.864+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/__main__.py", line 62, in main
    args.func(args)
[2025-01-12T19:03:34.865+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-01-12T19:03:34.866+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2025-01-12T19:03:34.867+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 61, in wrapper
    providers_configuration_loaded(func)(*args, **kwargs)
[2025-01-12T19:03:34.867+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/providers_configuration_loader.py", line 55, in wrapped_function
    return func(*args, **kwargs)
[2025-01-12T19:03:34.868+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 234, in worker
    _run_command_with_daemon_option(
[2025-01-12T19:03:34.869+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 47, in _run_command_with_daemon_option
    run_command_with_daemon_option(*args, **kwargs)
[2025-01-12T19:03:34.870+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/daemon_utils.py", line 86, in run_command_with_daemon_option
    callback()
[2025-01-12T19:03:34.870+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/cli/celery_command.py", line 227, in run_celery_worker
    celery_app.worker_main(options)
[2025-01-12T19:03:34.871+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 391, in worker_main
    self.start(argv=argv)
[2025-01-12T19:03:34.872+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/base.py", line 371, in start
    celery.main(args=argv, standalone_mode=False)
[2025-01-12T19:03:34.873+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
[2025-01-12T19:03:34.873+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
[2025-01-12T19:03:34.874+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
[2025-01-12T19:03:34.875+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
[2025-01-12T19:03:34.876+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/click/decorators.py", line 33, in new_func
    return f(get_current_context(), *args, **kwargs)
[2025-01-12T19:03:34.876+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bin/base.py", line 135, in caller
    return f(ctx, *args, **kwargs)
[2025-01-12T19:03:34.877+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bin/worker.py", line 356, in worker
    worker.start()
[2025-01-12T19:03:34.878+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/worker/worker.py", line 202, in start
    self.blueprint.start(self)
[2025-01-12T19:03:34.879+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 116, in start
    step.start(parent)
[2025-01-12T19:03:34.879+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/bootsteps.py", line 365, in start
    return self.obj.start()
[2025-01-12T19:03:34.880+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/base.py", line 130, in start
    self.on_start()
[2025-01-12T19:03:34.881+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/prefork.py", line 109, in on_start
    P = self._pool = Pool(processes=self.limit,
[2025-01-12T19:03:34.882+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 464, in __init__
    super().__init__(processes, *args, **kwargs)
[2025-01-12T19:03:34.882+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1046, in __init__
    self._create_worker_process(i)
[2025-01-12T19:03:34.883+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/concurrency/asynpool.py", line 482, in _create_worker_process
    return super()._create_worker_process(i)
[2025-01-12T19:03:34.883+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 1158, in _create_worker_process
    w.start()
[2025-01-12T19:03:34.886+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 120, in start
    self._popen = self._Popen(self)
[2025-01-12T19:03:34.887+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/context.py", line 331, in _Popen
    return Popen(process_obj)
[2025-01-12T19:03:34.888+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 22, in __init__
    self._launch(process_obj)
[2025-01-12T19:03:34.889+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/popen_fork.py", line 77, in _launch
    code = process_obj._bootstrap()
[2025-01-12T19:03:34.890+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 323, in _bootstrap
    self.run()
[2025-01-12T19:03:34.890+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/process.py", line 110, in run
    self._target(*self._args, **self._kwargs)
[2025-01-12T19:03:34.891+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 292, in __call__
    sys.exit(self.workloop(pid=pid))
[2025-01-12T19:03:34.892+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/billiard/pool.py", line 362, in workloop
    result = (True, prepare_result(fun(*args, **kwargs)))
[2025-01-12T19:03:34.892+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 651, in fast_trace_task
    R, I, T, Rstr = tasks[task].__trace__(
[2025-01-12T19:03:34.893+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 453, in trace_task
    R = retval = fun(*args, **kwargs)
[2025-01-12T19:03:34.893+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/celery/app/trace.py", line 736, in __protected_call__
    return self.run(*args, **kwargs)
[2025-01-12T19:03:34.894+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 141, in execute_command
    _execute_in_fork(command_to_exec, celery_task_id)
[2025-01-12T19:03:34.894+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/providers/celery/executors/celery_executor_utils.py", line 177, in _execute_in_fork
    args.func(args)
[2025-01-12T19:03:34.894+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-01-12T19:03:34.895+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2025-01-12T19:03:34.895+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-01-12T19:03:34.896+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 254, in _run_task_by_selected_method
    return _run_task_by_local_task_job(args, ti)
[2025-01-12T19:03:34.896+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 322, in _run_task_by_local_task_job
    ret = run_job(job=job_runner.job, execute_callable=job_runner._execute)
[2025-01-12T19:03:34.897+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
[2025-01-12T19:03:34.897+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 421, in run_job
    return execute_job(job, execute_callable=execute_callable)
[2025-01-12T19:03:34.898+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/job.py", line 450, in execute_job
    ret = execute_callable()
[2025-01-12T19:03:34.898+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/jobs/local_task_job_runner.py", line 171, in _execute
    self.task_runner.start()
[2025-01-12T19:03:34.898+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 55, in start
    self.process = self._start_by_fork()
[2025-01-12T19:03:34.899+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
[2025-01-12T19:03:34.899+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
[2025-01-12T19:03:34.900+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
[2025-01-12T19:03:34.900+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
[2025-01-12T19:03:34.900+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
[2025-01-12T19:03:34.901+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
[2025-01-12T19:03:34.901+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
[2025-01-12T19:03:34.902+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
[2025-01-12T19:03:34.902+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
[2025-01-12T19:03:34.903+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
[2025-01-12T19:03:34.903+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
[2025-01-12T19:03:34.903+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 762, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
[2025-01-12T19:03:34.904+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
[2025-01-12T19:03:34.904+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
[2025-01-12T19:03:34.905+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
[2025-01-12T19:03:34.905+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
[2025-01-12T19:03:34.906+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
[2025-01-12T19:03:34.908+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
[2025-01-12T19:03:34.909+0000] {logging_mixin.py:190} WARNING -   File "/opt/***/modules/main_sessions.py", line 63, in main_sessions
    logging.info('data_list df_sessions formed:', len(data_list))
[2025-01-12T19:03:34.910+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 2216, in info
    root.info(msg, *args, **kwargs)
[2025-01-12T19:03:34.910+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1539, in info
    self._log(INFO, msg, args, **kwargs)
[2025-01-12T19:03:34.910+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1684, in _log
    self.handle(record)
[2025-01-12T19:03:34.911+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1700, in handle
    self.callHandlers(record)
[2025-01-12T19:03:34.911+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1762, in callHandlers
    hdlr.handle(record)
[2025-01-12T19:03:34.912+0000] {logging_mixin.py:190} WARNING -   File "/usr/local/lib/python3.12/logging/__init__.py", line 1028, in handle
    self.emit(record)
[2025-01-12T19:03:34.912+0000] {logging_mixin.py:190} WARNING -   File "/home/***/.local/lib/python3.12/site-packages/***/utils/log/file_task_handler.py", line 274, in emit
    self.handler.emit(record)
[2025-01-12T19:03:34.912+0000] {logging_mixin.py:190} WARNING - Message: 'data_list df_sessions formed:'
Arguments: (1860042,)
[2025-01-12T19:05:19.661+0000] {main_sessions.py:74} INFO - всего к загрузке df_sessions: 1860042
[2025-01-12T19:05:20.422+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-01-12T19:05:20.437+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-12T19:05:20.438+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=sber_autopodpiska, task_id=main_sessions, run_id=manual__2025-01-12T18:43:11.976890+00:00, execution_date=20250112T184311, start_date=20250112T190250, end_date=20250112T190520
[2025-01-12T19:05:21.264+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-01-12T19:05:21.295+0000] {taskinstance.py:3895} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-01-12T19:05:22.132+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
